default: &default
  fluent_host:   <%= ENV['FLUENTD_HOST'] %>
  fluent_port:   24224
  tag:           'fdbk'
  messages_type: 'string'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
